version: "3.9"

services:
  totp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: totp-api

    ports:
      - "8080:8080"

    environment:
      TZ: "UTC"

    volumes:
      # Named volumes only
      - seed-data:/data
      - cron-output:/cron

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
