version: "3.9"

services:
  totp-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: totp-api

    ports:
      - "8080:8080"

    environment:
      TZ: "UTC"

    volumes:
      # Named volumes
      - seed-data:/data
      - cron-output:/cron

      # Read-only key files for development
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
